CC      = mpicc
LIBS = -lm
RM      = rm -f

ejercicio1: 
	$(CC) vectores.c ejercicio1.c -o ejercicio1  $(LIBS)

ejercicio2:
	$(CC) -o ejercicio2 ejercicio2.c $(LIBS)
ejercicio3:
	$(CC) -o ejercicio3 ejercicio3.c $(LIBS)
ejercicio4:
	$(CC) -o ejercicio4 ejercicio4.c $(LIBS)
ejercicio5:
	$(CC) -o ejercicio5 ejercicio5.c $(LIBS)
ejercicio6:
	$(CC) -o ejercicio6 ejercicio6.c $(LIBS)
ejercicio7:
	$(CC) -o ejercicio7 ejercicio7.c $(LIBS)
clean:
	$(RM) ejercicio1
	$(RM) ejercicio2
	$(RM) ejercicio3
	$(RM) ejercicio4
	$(RM) ejercicio5
	$(RM) ejercicio6
	$(RM) ejercicio7
